export const ADD_DOCTOR_DETAILS = 'ADD_DOCTOR_DETAILS';
export const ADD_DOCTOR_TIMING = 'ADD_DOCTOR_TIMING';
export const ADD_DOCTOR_FORM_RESET = 'ADD_DOCTOR_FORM_RESET';
export const TOGGLE_TAB = 'TOGGLE_TAB';
